### PR TITLE
Updated iframe to comment out android versions for now.

### PR DESCRIPTION
**Pull request by dougbevis**
Update to iFrame to comment out Android versions until we get a better long term answer.

### CODE REVIEW

**Comment by dougbevis** [comment]
@nicholaskillin @ReaganHelms  This is just a quick temp fix to not display the broken Android icons. I will create a new branch/PR once for a long term fix. This just needs to be merged and then bundled for upload.

**Comment by nicholaskillin** [comment]
@ReaganHelms I went ahead and created a new bundle in this branch that includes Doug's changes. Once you merge to master you should be able to pull the updated bundle from there.

**Comment by dougbevis** [comment]
@nicholaskillin  take a look at the new iframe and bundle.js files in my most recent commit. This should provide accurate up-to-the second info from both stores now. No throttling or issues that I can find. The bundle.js file is large, because I had to incorporate a bunch of dependencies from node modules into one file. This will replace the existing navigation.js file, and contain the js for the tabs, and the app store info.

**Comment by dougbevis** [comment]
Made changes requested by Nick above in the previous commit.

**Pull request merged**
